version: '3.8'

services:
  api:
    build:
      context: .
    container_name: api-moderation
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  bot:
    build:
      context: .
    container_name: bot-discord
    command: python bot/bot.py
    depends_on:
      - api
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
